=== pontocom/livroPHP/cap_19/bilhete_de_identidade.dtd
<?xml version='1.0'?>
<!ELEMENT BI (NUMERO-BI, EMISSAO, NOME, FILIACAO, NATURALIDADE, RESIDENCIA, DATA-DE-NASCIMENTO, ESTADO-CIVIL, ALTURA, VALIDADE)>

<!ELEMENT NUMERO-BI (NUMERO, DIGITO-CONTROLO)>
<!ELEMENT NUMERO (#PCDATA)>
<!ELEMENT DIGITO-CONTROLO (#PCDATA)>

<!ELEMENT EMISSAO (DATA, LOCAL)>
<!ELEMENT DATA (#PCDATA)>
<!ELEMENT LOCAL (#PCDATA)>

<!ELEMENT NOME (#PCDATA)>

<!ELEMENT FILIACAO (PAI, MAE)>
<!ELEMENT PAI (#PCDATA)>
<!ELEMENT MAE (#PCDATA)>

<!ELEMENT NATURALIDADE (FREGUESIA, CONCELHO)>
<!ELEMENT FREGUESIA (#PCDATA)>
<!ELEMENT CONCELHO (#PCDATA)>

<!ELEMENT RESIDENCIA (FREGUESIA, CONCELHO)>

<!ELEMENT DATA-DE-NASCIMENTO (#PCDATA)>

<!ELEMENT ESTADO-CIVIL (#PCDATA)>

<!ELEMENT ALTURA (#PCDATA)>

<!ELEMENT VALIDADE (#PCDATA)>

=== pontocom/livroPHP/cap_19/bi.xml
<?xml version='1.0'?>
<!DOCTYPE BI SYSTEM "bilhete_de_identidade.dtd">

<BI>
	<NUMERO-BI>
		<NUMERO>10033445</NUMERO>
		<DIGITO-CONTROLO>3</DIGITO-CONTROLO>
	</NUMERO-BI>
	
	<EMISSAO>
		<DATA>22/09/2003</DATA>
		<LOCAL>Lisboa</LOCAL>
	</EMISSAO>
	<NOME>Carlos Jose Corredoura Serrao</NOME>
	<FILIACAO>
		<PAI>Carlos Manuel Serrao</PAI>
		<MAE>Maria Norlinda dos Santos Corredoura Serrao</MAE>
	</FILIACAO>
	<NATURALIDADE>
		<FREGUESIA>S. Sebastiao da Pedreira</FREGUESIA>
		<CONCELHO>Lisboa</CONCELHO>
	</NATURALIDADE>
	<RESIDENCIA>
		<FREGUESIA>Feijo</FREGUESIA>
		<CONCELHO>Almada</CONCELHO>
	</RESIDENCIA>
	<DATA-DE-NASCIMENTO>06/01/1973</DATA-DE-NASCIMENTO>
	<ESTADO-CIVIL>Casado</ESTADO-CIVIL>
	<ALTURA>1,78</ALTURA>
	<VALIDADE>05/05/2009</VALIDADE>
</BI>

=== pontocom/livroPHP/cap_19/teste.xml
<?xml version='1.0'?>
<!DOCTYPE BI SYSTEM "bilhete_de_identidade.dtd">

<BI>
	<NUMERO-BI>
		<NUMERO>10033445</NUMERO>
		<DIGITO-CONTROLO>3</DIGITO-CONTROLO>
	</NUMERO-BI>
	
	<EMISSAO>
		<DATA>22/09/2003</DATA>
		<LOCAL>Lisboa</LOCAL>
	</EMISSAO>
	<NOME>Carlos Jose Corredoura Serrao</NOME>
	<FILIACAO>
		<PAI>Carlos Manuel Serrao</PAI>
		<MAE>Maria Norlinda dos Santos Corredoura Serrao</MAE>
	</FILIACAO>
	<NATURALIDADE>
		<FREGUESIA>S. Sebastiao da Pedreira</FREGUESIA>
		<CONCELHO>Lisboa</CONCELHO>
	</NATURALIDADE>
	<RESIDENCIA>
		<FREGUESIA>Feijo</FREGUESIA>
		<CONCELHO>Almada</CONCELHO>
	</RESIDENCIA>
	<DATA-DE-NASCIMENTO>06/01/1973</DATA-DE-NASCIMENTO>
	<ESTADO-CIVIL>Casado</ESTADO-CIVIL>
	<ALTURA>1,78</ALTURA>
	<VALIDADE>05/05/2009</VALIDADE>
	<NUMERO-BI>
		<NUMERO>123456</NUMERO>
		<DIGITO-CONTROLO>9</DIGITO-CONTROLO>
	</NUMERO-BI>
	
	<EMISSAO>
		<DATA>22/09/2004</DATA>
		<LOCAL>Lisboa</LOCAL>
	</EMISSAO>
	<NOME>Joaquim Marques</NOME>
	<FILIACAO>
		<PAI>Jose Marques</PAI>
		<MAE>Celeste marques</MAE>
	</FILIACAO>
	<NATURALIDADE>
		<FREGUESIA>Povoa de Varzim</FREGUESIA>
		<CONCELHO>Povoa de Varzim </CONCELHO>
	</NATURALIDADE>
	<RESIDENCIA>
		<FREGUESIA>C.Branco</FREGUESIA>
		<CONCELHO>C.Branco</CONCELHO>
	</RESIDENCIA>
	<DATA-DE-NASCIMENTO>01/01/1961</DATA-DE-NASCIMENTO>
	<ESTADO-CIVIL>Casado</ESTADO-CIVIL>
	<ALTURA>1,75</ALTURA>
	<VALIDADE>05/10/2011</VALIDADE>
</BI>
